/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/button/BaseButton.vue')['default']
    BaseCollapse: typeof import('./src/components/base/collapse/BaseCollapse.vue')['default']
    BaseDialog: typeof import('./src/components/base/dialog/BaseDialog.vue')['default']
    BaseDrawer: typeof import('./src/components/base/drawer/BaseDrawer.vue')['default']
    BaseEmpty: typeof import('./src/components/base/empty/BaseEmpty.vue')['default']
    BaseIcon: typeof import('./src/components/base/icon/BaseIcon.vue')['default']
    BaseInput: typeof import('./src/components/base/input/BaseInput.vue')['default']
    BaseLoading: typeof import('./src/components/base/loading/BaseLoading.vue')['default']
    BaseLoadingCard: typeof import('./src/components/base/loading/BaseLoadingCard.vue')['default']
    BasePagination: typeof import('./src/components/base/pagination/BasePagination.vue')['default']
    BaseSelect: typeof import('./src/components/base/select/BaseSelect.vue')['default']
    BaseTab: typeof import('./src/components/base/tab/BaseTab.vue')['default']
    BaseTable: typeof import('./src/components/base/table/BaseTable.vue')['default']
    DialogConfirm: typeof import('./src/components/base/dialog/DialogConfirm.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    LoadingCard: typeof import('./src/components/base/loading/LoadingCard.vue')['default']
    OtpInput: typeof import('./src/components/base/otp/OtpInput.vue')['default']
    QuantityInput: typeof import('./src/components/base/quantity/QuantityInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
