services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    platform: linux/arm64
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: 19110919

    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    platform: linux/arm64
    command: ['redis-server', '--requirepass', 'root_admin', '--ignore-warnings', 'ARM64-COW-BUG']
    environment:
      REDIS_PASSWORD: root_admin
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - cluster.name=docker-cluster
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'

  BeautyBox:
    image: presidentquyen/beauty_box:v1.0.0
    platform: linux/arm64
    container_name: BeautyBox
    depends_on:
      - redis
      - mysql
    ports:
      - '8080:8080'
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/beauty_box?createDatabaseIfNotExist=true
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: 19110919
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PASSWORD: root_admin
      ELASTIC_HOSTS: elasticsearch:9200
volumes:
  redis_data:
  mysql_data:
  es_data:
